### ISSUE TITLE
Issue with Advance Search

### ISSUE THREAD

**Issue by ngohoangminhdang1998** [mehranahmadifar/advancedsearch#1]
Hi mehranahmadifar,

i have 2 questions that i need you to support.
the first question:
I'm trying to using your managed solution, but when i imported this solution in my environment (CRM 9.2), it had the issue below.
![image](https://user-images.githubusercontent.com/56905206/145246783-4c2fd99a-96e2-443a-9e56-794b0a544c1a.png)
Now i use Online version, so there is a plugin inside your project registing with None mode ( Full Mode Trust) and i can not import it. 
the second question: 
Do i have to pay money for this solution ?
Please help me for that.
Thanks and Best Regards,
Teddy

**Comment by mehranahmadifar** [comment]
Hi Teddy,
this solution is fully free and for get version of your environment please email me.
Email: MehranAhmadifar@gmail.com

Best Regards.
